### ISSUE TITLE
Incomplete help documentation

### ISSUE THREAD

**Issue by Entomy** [psyomn/gnatgen#3]
```
PS C:\Users\p-kel\Desktop\gnatgen\bin> .\gnatgen --help
Did not understand that
PS C:\Users\p-kel\Desktop\gnatgen\bin> .\gnatgen
Use:
gnatgen <action> [params]
  new project - to create a template of a new project
```

As seen, `--help` is not recognized and the help documentation that is printed out is incomplete, as the `README.md` is using "actions" such as `print` and `p`.

**Comment by psyomn** [comment]
So, the way that flag parsing is done right now is not super optimal. Right now only "help" is detected, and it's not the gnu like format. We can push to change this if you want, let me know!

**Comment by Entomy** [comment]
Yeah I'm finishing up the video then I'll get to making some changes to improve things. While I'm at it, do I have your permission to package this for distribution (chocolatey, Linux packages, etc)? Preferably license your code, otherwise I'll treat it as all rights reserved.

**Comment by psyomn** [comment]
I don't mind packaging, but I'd suggest there's some rigorous testing before this gets distributed, as I don't remember if I did any nasty things a while ago in here (won't hurt to double check). I'll be adding a BSD-2 license possibly tonight (in around 7 hours or so), if you're OK with waiting until then.

**Comment by Entomy** [comment]
Yeah absolutely. It'll be a few days while I make changes and set up some unit tests.
