### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by Entomy** [psyomn/gnatgen#8]
Per [this comment](https://github.com/psyomn/gnatgen/pull/6#pullrequestreview-229332700) a new name should be considered.

**Comment by Entomy** [comment]
I'm waiting on this for Chocolatey (Windows) and Pacman (Arch Linux) packages. Idgaf what the name is, you just mentioned reconsidered it and I'll hold out until you decide.

**Comment by psyomn** [comment]
Going with agen; I don't think anything uses that name.
